config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :time
  resources :date

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/date_controller.rb
class DateController < HomeController

  def index
    @date = DateTime.now
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @time = Time.now
    @date = DateTime.now
  end

end

app/controllers/time_controller.rb
class TimeController < HomeController

  def index
    @time = Time.now
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/date/index.html.erb
<h1>Q: What is the date?</h1>
<h1>A: <%= @date.strftime('%A, %B %d, %Y') %></h1>

<p>The year is: <%= @date.strftime('%Y') %> (or '<%= @date.strftime('%y') %> if you're lazy)...</p>
<p>The month is: <%= @date.strftime('%B') %> (and we all know <%= @date.strftime('%b') %> is month <%= @date.strftime('%m') %> of the year)...</p>
<p>Today is day <%= @date.strftime('%d') %> of the month but day <%= @date.strftime('%w') %> of the week...</p>
<p>Which, of course, is <%= @date.strftime('%A') %> (or <%= @date.strftime('%a') %> if you really can't be bothered)...</p>

<p class="note"><%= link_to "Refresh", date_index_path %><br>
(Though, hey, you know it's still gonna be today, right?)</p>

<p class="note"><%= link_to "home", root_path %></p>

app/views/home/index.html.erb
<h1>It's <%= @time.strftime('%A, %B %d, %Y %I:%M:%S %Z') %></h1>
<p class="note">Break down the <%= link_to "date", date_index_path %> | Break down the <%= link_to "time", time_index_path %></p>


<p class="note"><em>Things that remain: Time zones... yikes! &middot; Date.new and strptime &middot; Other built-in methods for date and time manipulation<br>
The surface has only been scratched.</em></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Datetime</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/time/index.html.erb
<h1>Q: What time is it?</h1>
<h1>A: <%= @time.strftime('%I:%M:%S %p %Z') %></h1>

<p>The hour is: <%= @time.strftime('%I') %> (or <%= @time.strftime('%H') %> if you use the 24 hour clock)...</p>

<p>The minute is: <%= @time.strftime('%M') %>...</p>

<p>We're <%= @time.strftime('%S') %> seconds into that minute...</p>

<p>It's currently <%= @time.strftime('%p') %>...

<p>And this is coming to you from <%= @time.strftime('%Z') %> (time zone)...</p>

<p>Tomorrow begins in <%= @time.end_of_day - @time %> seconds...</p>

<p class="note"><%= link_to "Refresh", time_index_path %>
<p class="note"><%= link_to "home", root_path %></p>